[workspace]
resolver = "1"
members = [
    "proton-pass-common",
    "proton-pass-mobile",
    "proton-pass-web",
    "proton-pass-derive"
]

[profile.release]
opt-level = "s" # Tell `rustc` to optimize for small code size.
