[package]
name = "proton-pass-common"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
email_address = "0.2.4"
proton-pass-derive = { path = "../proton-pass-derive" }
uriparse = "0.6.4"
url = "2.4.1"
queryst = "3.0.0"
serde_json = "1.0.107"