[package]
name = "proton-pass-common"
version = "0.3.3"
edition = "2021"

[lib]
doctest = false

[dependencies]
email_address = "0.2.4"
getrandom = { version = "0.2.10", features = ["js"] }
passwords = "3.1.16"
proton-pass-derive = { path = "../proton-pass-derive" }
rand = "0.8.5"
url = "2.4.1"
serde-querystring = "0.2.1"
serde = { version = "1.0.188", features = ["derive"] }
totp-rs = "5.4.0"
regex = "1.10.2"
luhn = "1.0.1"
