[package]
name = "proton-pass-common"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
email_address = "0.2.4"
passwords = "3.1.16"
proton-pass-derive = { path = "../proton-pass-derive" }
rand = "0.8.5"
url = "2.4.1"
serde-querystring = "0.2.1"
serde = { version = "1.0.188", features = ["derive"] }