[package]
name = "proton-pass-common"
version = "0.11.2"
edition = "2021"

[lib]
doctest = false

[dependencies]
proton-pass-derive = { path = "../proton-pass-derive" }

aes = "0.7.5"
aes-gcm = "0.10.3"
async-trait = "0.1.74"
base32 = "0.5.1"
base64 = "0.22.0"
block-modes = "0.8.1"
block-padding = "0.3"
coset = "0.3.8"
csv = "1.3.1"
email_address = "0.2.9"
file-format = { version = "0.26.0", features = ["reader"] }
getrandom = { version = "0.2.10", features = ["js"] }
hex = "0.4.3"
hmac-sha1 = "0.2.2"
hmac = "0.12"
lazy_static = "1.5.0"
luhn = "1.0.1"
passkey = "0.4.0"
passkey-authenticator = { version = "0.4.0", features = ["testable"] }
passkey-types = { version = "0.4.0", features = ["serialize_bytes_as_base64_string"] }
passwords = "3.1.16"
pbkdf2 = "0.11"
protobuf = "3.7.1"
public-suffix = "0.1.2"
rand = "0.8.5"
regex-lite = "0.1.5"
rmp-serde = "1.1.2"
scrypt = "0.11.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.111"
serde-querystring = "0.2.1"
sha2 = "0.10"
totp-rs = "5.6.0"
url = "2.5.4"


[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
tokio = { version = "1.36", features = ["rt"]}

[build-dependencies]
protobuf-codegen = "3.7.1"
protoc-bin-vendored = "3.1.0"


[[bench]]
name = "card_detector"
harness = false

[[bench]]
name = "password_scorer"
harness = false
