[package]
name = "proton-pass-web"
version = "0.7.9"
edition = "2021"

[lib]
doctest = false
crate-type = ["cdylib", "rlib"]

[dependencies]
proton-pass-common = { path = "../proton-pass-common" }

console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3.67"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.36", features = ["rt"] }
tsify = { version = "0.4.5", features = ["js"] }
wasm-bindgen = "0.2.92"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
[features]
default = ["console_error_panic_hook"]
